edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_arm_leading_pipes = "Never"
force_explicit_abi = true
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
hex_literal_case = "Lower"
empty_item_single_line = true
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"